Disable "gen_doc" alias for document command
When set, this alias is causing the following error:

> argparse.ArgumentError: argument COMMAND: conflicting subparser alias: gen_doc

It appears to conflict with the `view` command

Likely due to some change in the argparse module of recent Python
distributions.